### ISSUE TITLE
Make rust version a single workflow variable

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/operator-templating#310]
It would be better to change the version in one place, instead across many steps.

Example (stripped for brevity and clarity):

```yml
env:
  RUST_TOOLCHAIN_VERSION: "1.75.0"

jobs:
  run_clippy:
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          components: clippy
```

`operator-rs` already does so:
- https://github.com/stackabletech/operator-rs/blob/407cfec12469dba32ac1795a9ce7e62077a0650b/.github/workflows/build.yml#L20
- https://github.com/stackabletech/operator-rs/blob/407cfec12469dba32ac1795a9ce7e62077a0650b/.github/workflows/build.yml#L86-L89
